# Unique key of the project on SonarCloud. Usually "owner_repo".
sonar.projectKey=HaTranBK_image_generator
# Organization key on SonarCloud. Usually your GitHub username or organization name in lowercase.
sonar.organization=HaTranBK

# This is the name and version that are displayed in the SonarCloud UI.
sonar.projectName=image_generator
sonar.projectVersion=1.0.0

# Path to the source directories.
sonar.sources=backend/src,frontend/src
# Path to the test files.
sonar.tests=backend/src
sonar.test.inclusions=backend/src/**/*.spec.ts

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclude third-party libraries, build folders and generated files from analysis
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,backend/coverage/**,frontend/out/**,backend/prisma/migrations/**

# Paths to coverage reports.
# Since we run Jest with coverage in backend, we reference its lcov report.
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
